apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: member
  labels:
    app: frontend
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 034362047320.dkr.ecr.ap-northeast-2.amazonaws.com/cwave01/front:latest  
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://a2f3b47d8b1b9400ca2981031f0b9995-134946597.ap-northeast-2.elb.amazonaws.com:8080"
      imagePullSecrets:
        - name: ecr-secret  
