apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: member
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # ALB를 통해 접근
